const { dvdauthorXml } = require('./author.js');

// Single-layer DVD±R: 2,295,104 blocks x 2048 bytes (drutil status on a blank).
const DVD5_BYTES = 4700372992;

const PROBE = ['-fflags', '+genpts', '-analyzeduration', '200M', '-probesize', '200M'];

// Soft-telecined NTSC film -> hard-telecined 29.97i MPEG-2. ffmpeg can't write
// soft pulldown flags and dvdauthor rejects 23.976 for NTSC, so: force the
// decoded frames back to 23.976, then 3:2 telecine. `-top` is gone because
// ffmpeg 9 rejects it; there the telecine filter's top-first flag carries
// through. ffmpeg 6.1 writes bottom-first instead, hence check_field_order.
function ntscFilmVideoArgs({ bitrate, aspect }) {
  return [
    '-vf', 'fps=24000/1001,telecine=pattern=23',
    '-c:v', 'mpeg2video', '-b:v', bitrate, '-maxrate', '8000k', '-bufsize', '1835k',
    '-g', '18', '-bf', '2', '-flags', '+ilme+ildct', '-alternate_scan', '1',
    '-mbd', 'rd', '-trellis', '1', '-cmp', '2', '-subcmp', '2',
    '-aspect', aspect, '-pix_fmt', 'yuv420p',
  ];
}

const concat = (inputs) => `concat:${inputs.join('|')}`;

function encodePass1Argv(step) {
  return ['ffmpeg', '-y', ...PROBE, '-i', concat(step.inputs), '-map', '0:v:0',
    ...ntscFilmVideoArgs(step), '-pass', '1', '-f', 'null', '-'];
}

function encodePass2Argv(step) {
  const maps = step.maps.flatMap((m) => ['-map', m]);
  return ['ffmpeg', '-y', ...PROBE, '-i', concat(step.inputs), '-map', '0:v:0', ...maps,
    ...ntscFilmVideoArgs(step), '-pass', '2', '-c:a', 'copy', '-c:s', 'copy', '-f', 'dvd', step.out];
}

function remuxArgv(step) {
  return ['ffmpeg', '-y', '-hide_banner', '-loglevel', 'warning', ...PROBE, '-i', concat(step.inputs),
    '-map', '0:v:0', '-map', '0:a', '-c', 'copy', '-f', 'dvd', step.out];
}

function extractTitleArgv(step) {
  return ['dvdbackup', '-i', '$SRC', '-o', 't', '-t', String(step.title), '-n', `T${step.title}`];
}

function isoArgv(disc) {
  return ['hdiutil', 'makehybrid', '-udf', '-udf-volume-name', disc.volume, '-o', disc.iso, `${disc.dir}/`];
}

function q(arg) {
  if (arg === '$SRC') return '"$SRC"';
  return /^[\w\-+=:.,/@%]+$/.test(arg) ? arg : `'${arg.replace(/'/g, `'\\''`)}'`;
}

const sh = (argv) => argv.map(q).join(' ');

const HELPERS = `check_duration() { # file expected_ms tolerance_ms
  local got; got=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$1")
  awk -v g="$got" -v e="$2" -v t="$3" -v f="$1" 'BEGIN {
    d = g * 1000 - e; if (d < 0) d = -d
    if (d > t) { printf "VERIFY FAIL %s: %.0f ms, expected %d ms\\n", f, g * 1000, e; exit 1 }
    printf "verify ok   %s: %.0f ms (expected %d ms)\\n", f, g * 1000, e }'
}
check_field_order() { # file expected (tt = top first)
  local got; got=$(ffprobe -v error -select_streams v:0 -show_entries stream=field_order -of default=nw=1:nk=1 "$1")
  [ "$got" = "$2" ] || { echo "VERIFY FAIL $1: field order $got, expected $2"; exit 1; }
  echo "verify ok   $1: field order $got"
}
check_fits() { # iso capacity_bytes
  local size; size=$(wc -c < "$1" | tr -d ' ')
  [ "$size" -gt 0 ] && [ "$size" -le "$2" ] || { echo "VERIFY FAIL $1: $size bytes, capacity $2"; exit 1; }
  echo "verify ok   $1: $size bytes <= $2"
}`;

function stepScript(step, recipe) {
  switch (step.run) {
    case 'copy-vobs':
      return [
        `mkdir -p ${q(step.to)}`,
        `cp ${step.files.map((f) => `"$SRC/VIDEO_TS/${f}"`).join(' ')} ${q(step.to)}/`,
      ];
    case 'encode-2pass':
      return [
        sh(encodePass1Argv(step)),
        sh(encodePass2Argv(step)),
        `check_field_order ${q(step.out)} tt`,
        `check_duration ${q(step.out)} ${step.expectedMs} ${recipe.durationToleranceMs}`,
      ];
    case 'extract-title':
      return [sh(extractTitleArgv(step))];
    case 'remux':
      return [sh(remuxArgv(step)), `check_duration ${q(step.out)} ${step.expectedMs} ${recipe.durationToleranceMs}`];
    case 'author': {
      const disc = recipe.discs.find((d) => d.id === step.disc);
      return [
        `cat > ${disc.xml} <<'XML'\n${dvdauthorXml(disc)}XML`,
        `rm -rf ${q(disc.dir)} && VIDEO_FORMAT=NTSC dvdauthor -x ${disc.xml}`,
        `[ -f ${q(disc.dir)}/VIDEO_TS/VIDEO_TS.IFO ] || { echo "VERIFY FAIL dvdauthor: no ${disc.dir}/VIDEO_TS/VIDEO_TS.IFO"; exit 1; }`,
      ];
    }
    case 'iso': {
      const disc = recipe.discs.find((d) => d.id === step.disc);
      return [
        `rm -f ${q(disc.iso)}`,
        sh(isoArgv(disc)),
        `check_fits ${q(disc.iso)} ${DVD5_BYTES}`,
        `echo "burn when ready: drutil status && hdiutil burn -speed 4 ${disc.iso}"`,
      ];
    }
    default:
      throw new Error(`unknown step: ${step.run}`);
  }
}

function buildScript(recipe) {
  const workdir = recipe.workdir.replace(/^~(?=\/|$)/, '$HOME');
  const out = [
    '#!/usr/bin/env bash',
    `# Generated by mr-img dvd/script.js from recipe "${recipe.id}".`,
    '# Run under caffeinate on macOS: a sleeping Mac stalls the encode for hours.',
    'set -euo pipefail',
    `SRC=${q(recipe.source)}`,
    `mkdir -p "${workdir}" && cd "${workdir}"`,
    '',
    HELPERS,
  ];
  for (const step of recipe.steps) {
    out.push('', `# --- ${step.run}${step.note ? `: ${step.note}` : ''}`, ...stepScript(step, recipe));
  }
  return out.join('\n') + '\n';
}

module.exports = {
  DVD5_BYTES, ntscFilmVideoArgs, encodePass1Argv, encodePass2Argv, remuxArgv,
  extractTitleArgv, isoArgv, buildScript,
};
